server:
  port: 8085
  servlet:
    context-path: /api


spring:
  profiles:
    default: ${SPRING_PROFILES_ACTIVE}
  application:
    name: starter-package
  datasource:
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: ${FLYWAY}
  management:
    endpoints:
      web:
        exposure:
          include: health
security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000}

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
    path: /v3/api-docs
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    persist-authorization: true
