server:
  port: 8085
  servlet:
    context-path: /api


spring:
  application:
    name: starter-package
  datasource:
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: ${FLYWAY}
  management:
    endpoints:
      web:
        exposure:
          include: health
security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000}